version: 2.1

jobs:
  build-docker-image:
    docker:

      - image: cimg/base:stable
    steps:
      - checkout


      - setup_remote_docker:
          docker_layer_caching: true


      - run:
          name: Build Docker Image
          command: |
            # Example tag using the commit SHA
            docker build -t myorg/node-js-sample:$CIRCLE_SHA1 .

workflows:
  build_and_test:
    jobs:
      - build-docker-image
