version: 2.1

jobs:
  build_test_and_push:
    machine:
      image: ubuntu-2204:current

    steps:
      # Step 1: Check out code
      - checkout

      # Step 2: Build Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t galoux/node-js-sample:$CIRCLE_SHA1 .

      # Step 3: Run the container in background
      - run:
          name: Run Container
          command: |
            docker run -d -p 8080:8080 --name testcontainer galoux/node-js-sample:$CIRCLE_SHA1
            # Give the container time to start
            sleep 10

      # Step 4: Test the container
      - run:
          name: Test Container
          command: |
            curl -f http://127.0.0.1:8080
            echo "✅ Container responded successfully!"

      # Step 5: Stop and remove the container
      - run:
          name: Stop Container
          command: |
            docker stop testcontainer
            docker rm testcontainer

      # Step 6: Push the image to Docker Hub
      # Only runs if the previous steps (build + test) succeed
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push galoux/node-js-sample:$CIRCLE_SHA1

workflows:
  build_test_and_push_workflow:
    jobs:
      - build_test_and_push
