version: 2.1

jobs:
  build_and_test_image:
    docker:
      # Use a lightweight CircleCI image that supports Docker
      - image: cimg/base:stable

    steps:
      # Step 1: Check out your code
      - checkout

      # Step 2: Enable Docker (for building/running containers)
      - setup_remote_docker:
          docker_layer_caching: true

      # Step 3: Build the Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t node-js-sample .

      # Step 4: Run the container in the background
      - run:
          name: Run Container
          command: |
            # -d runs it in the background
            docker run -d -p 8080:8081 --name testcontainer node-js-sample
            # Give the container a few seconds to initialize
            sleep 10

      # Step 5: Test the container by curling inside it
      - run:
          name: Test Container
          command: |
            # Run curl INSIDE the container, checking the server on port 8080
            curl -f http://127.0.0.1:8080
            echo "✅ Container responded successfully!"

      # Step 6: (Optional) Stop the container explicitly 
      - run:
          name: Stop Container
          command: |
            docker stop testcontainer
            docker rm testcontainer


workflows:
  build_and_test:
    jobs:
      - build_and_test_image
