version: 2.1

jobs:
  build_and_test_image:
    machine:
      # Utilise l'image Ubuntu 22.04 fournie par CircleCI
      image: ubuntu-2204:current

    steps:
      # Étape 1 : Récupération du code
      - checkout

      # Étape 2 : Construction de l'image Docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t node-js-sample .

      # Étape 3 : Lancement du conteneur en arrière-plan
      - run:
          name: Run Container
          command: |
            # -d : détaché (arrière-plan)
            # -p 8080:8080 : mappe le port 8080 du conteneur au port 8080 de la machine
            docker run -d -p 8080:8080 --name testcontainer node-js-sample
            # Attendre quelques secondes que l'app soit réellement prête
            sleep 10

      # Étape 4 : Test du conteneur (on curl le host local sur le port 8080)
      - run:
          name: Test Container
          command: |
            curl -f http://127.0.0.1:8080
            echo "✅ Container responded successfully!"

      # Étape 5 : Arrêt et nettoyage
      - run:
          name: Stop Container
          command: |
            docker stop testcontainer
            docker rm testcontainer

workflows:
  build_and_test:
    jobs:
      - build_and_test_image
